import React from "react";
import { Link } from "react-router-dom";
import useStore from "../store";
function Landing() {
  const user = useStore((s) => s.user);
  return /* @__PURE__ */ React.createElement("div", { className: "max-w-4xl mx-auto mt-12 p-8 bg-white dark:bg-slate-800 rounded" }, /* @__PURE__ */ React.createElement("div", { className: "grid md:grid-cols-2 gap-6 items-center" }, /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("h1", { className: "text-4xl font-bold mb-4" }, "Campus Events, made simple"), /* @__PURE__ */ React.createElement("p", { className: "text-slate-600 dark:text-slate-300 mb-6" }, "Discover student clubs, talks, workshops and festivals. Join events, track your XP, and create events for your club."), /* @__PURE__ */ React.createElement("div", { className: "flex gap-3" }, /* @__PURE__ */ React.createElement(Link, { to: "/signup", className: "px-4 py-2 bg-brand text-white rounded" }, "Get started"), /* @__PURE__ */ React.createElement(Link, { to: "/login", className: "px-4 py-2 border rounded" }, "Sign in"), /* @__PURE__ */ React.createElement(Link, { to: "/", className: "px-4 py-2 text-sm text-slate-500 rounded" }, "Explore public events"))), /* @__PURE__ */ React.createElement("div", { className: "hidden md:block h-56 md:h-72 lg:h-80 overflow-visible" }, /* @__PURE__ */ React.createElement("div", { className: "h-full rounded overflow-visible shadow relative" }, /* @__PURE__ */ React.createElement("img", { src: "/assets/landing.jpg", alt: "landing", className: "w-full object-cover absolute left-0 top-0 h-[130%] md:h-[140%] lg:h-[150%] object-top" })))), /* @__PURE__ */ React.createElement("div", { className: "mt-8" }, /* @__PURE__ */ React.createElement("h3", { className: "text-xl font-semibold mb-2" }, "Why use CampusEvents?"), /* @__PURE__ */ React.createElement("ul", { className: "list-disc pl-5 text-slate-600 dark:text-slate-300" }, /* @__PURE__ */ React.createElement("li", null, "Find events by interest or department"), /* @__PURE__ */ React.createElement("li", null, "Create and manage events in minutes"), /* @__PURE__ */ React.createElement("li", null, "Earn XP for attending and participating"))));
}
export {
  Landing as default
};
